[package]
name = "release"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
git2 = "0.20.2"
semver = "1.0.26"

[build-dependencies]
anyhow = "1.0.98"
vergen-git2 = "1.0.7"
